# ezmkinitcpio configuration for Nyarch Hyprland ISO
# SPDX-License-Identifier: GPL-3.0-or-later
# This is used by the ezarcher build system after installation.

HOOKS=(base udev plymouth autodetect microcode modconf kms keyboard keymap consolefont block resume filesystems fsck)
