---
modules-search: [ /usr/lib/calamares/modules ]
instances:
  - id:       finished
    module:   finishedq
    config:
      restartNowEnabled: false
      restartNowCommand: "systemctl reboot"
---
- bootloader
- displaymanager
- fstab
- grubcfg
- initcpio
- initcpiocfg
- keyboard
- locale
- luksopenswaphookcfg
- machineid
- mount
- openrcdmcryptcfg
- packages
- partition
- removeuser
- services-systemd
- shellprocess-ezfinish
- shellprocess-mvezmkinit
- unpackfs
- users
- welcome
